<a href="https://colab.research.google.com/github/petergaoxl/PytorchProject/blob/main/Intro_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00. Pytorch foundamentals

In [6]:
import torch
import numpy as np


In [11]:
np1 = np.array([1,2,3,4,5])
print(np1)
print(np1.dtype)

[1 2 3 4 5]
int64


In [18]:
np2 = np.random.rand(3,4)
np2


array([[0.39256176, 0.00190533, 0.63330591, 0.2494045 ],
       [0.77969306, 0.92655771, 0.50856961, 0.81302322],
       [0.27467388, 0.32358661, 0.61043034, 0.36883405]])

In [17]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.4250,  1.8246,  0.6712, -0.3913],
        [-0.1488,  0.8778, -0.1380, -0.3079],
        [ 1.6948, -0.3632, -0.5075,  0.7545]])