<a href="https://colab.research.google.com/github/petergaoxl/PytorchProject/blob/main/Intro_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00. Pytorch foundamentals

In [6]:
import torch
import numpy as np


In [11]:
np1 = np.array([1,2,3,4,5])
print(np1)
print(np1.dtype)

[1 2 3 4 5]
int64


In [18]:
np2 = np.random.rand(3,4)
np2


array([[0.39256176, 0.00190533, 0.63330591, 0.2494045 ],
       [0.77969306, 0.92655771, 0.50856961, 0.81302322],
       [0.27467388, 0.32358661, 0.61043034, 0.36883405]])

In [28]:
tensor_2d = torch.randn(3,4)
print(tensor_2d)
tensor_2d.dtype

tensor([[ 0.7467,  0.3384, -0.0550, -1.0091],
        [ 1.2785,  1.1042,  1.0719, -0.3966],
        [-0.3028,  0.9466,  0.3794, -0.7145]])


torch.float32

In [21]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
#  Create tensor out of numpy array
tenarr_np = torch.tensor(np2)
tenarr_np

tensor([[0.3926, 0.0019, 0.6333, 0.2494],
        [0.7797, 0.9266, 0.5086, 0.8130],
        [0.2747, 0.3236, 0.6104, 0.3688]], dtype=torch.float64)