<a href="https://colab.research.google.com/github/petergaoxl/PytorchProject/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#  Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
#  Reshape if we dont't know the number of items using -1
torch2 = torch.arange(15)
torch2
torch2 = torch2.reshape(3,-1)
torch2 = torch2.reshape(-1,5)
torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

**View**

In [8]:
torch3 = torch.arange(10)
torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
torch4 = torch3.view(2,5)
torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
#  What's the difference between shape and view?
torch5 = torch.arange(10)
torch5

NameError: name 'torch' is not defined

In [16]:
torch6 = torch5.view(2,5)
torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
#  Change torch 5
torch5[2] = 1988
torch5

NameError: name 'torch5' is not defined

In [ ]:
# Slices