<a href="https://colab.research.google.com/github/petergaoxl/PytorchProject/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#  Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
#  Reshape if we dont't know the number of items using -1
torch2 = torch.arange(15)
torch2
torch2 = torch2.reshape(3,-1)
torch2 = torch2.reshape(-1,5)
torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])